/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface HoldingDTO {
  'id' : HoldingId,
  'name' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'quantity' : number,
  'costBasis' : number,
  'walletAddressLabel' : string,
  'symbol' : string,
}
export type HoldingId = bigint;
export interface PlatformStats {
  'activeUsers' : bigint,
  'totalHoldings' : bigint,
  'totalUsers' : bigint,
  'suspendedUsers' : bigint,
  'totalTransactions' : bigint,
}
export interface ReferralLeaderboardEntry {
  'username' : string,
  'referralCount' : bigint,
}
export interface ReferralStats {
  'referredUsers' : Array<string>,
  'referralCount' : bigint,
}
export interface TransactionDTO {
  'id' : TransactionId,
  'priceAtTime' : number,
  'transactionType' : { 'buy' : null } |
    { 'sell' : null },
  'totalValue' : number,
  'date' : bigint,
  'notes' : string,
  'quantity' : number,
  'symbol' : string,
}
export type TransactionId = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addHolding' : ActorMethod<
    [string, string, number, number, string],
    HoldingId
  >,
  'addTransaction' : ActorMethod<
    [
      string,
      { 'buy' : null } |
        { 'sell' : null },
      number,
      number,
      number,
      string,
    ],
    TransactionId
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteTransaction' : ActorMethod<[TransactionId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  'getPrices' : ActorMethod<[], string>,
  'getReferralLeaderboard' : ActorMethod<[], Array<ReferralLeaderboardEntry>>,
  'getReferralStats' : ActorMethod<[UserId], ReferralStats>,
  'getUserHoldings' : ActorMethod<[UserId], Array<HoldingDTO>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTransactions' : ActorMethod<[UserId], Array<TransactionDTO>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeHolding' : ActorMethod<[HoldingId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateHolding' : ActorMethod<
    [HoldingId, string, string, number, number, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];