/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const HoldingId = IDL.Nat;
export const TransactionId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PlatformStats = IDL.Record({
  'activeUsers' : IDL.Nat,
  'totalHoldings' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'suspendedUsers' : IDL.Nat,
  'totalTransactions' : IDL.Nat,
});
export const ReferralLeaderboardEntry = IDL.Record({
  'username' : IDL.Text,
  'referralCount' : IDL.Nat,
});
export const UserId = IDL.Principal;
export const ReferralStats = IDL.Record({
  'referredUsers' : IDL.Vec(IDL.Text),
  'referralCount' : IDL.Nat,
});
export const HoldingDTO = IDL.Record({
  'id' : HoldingId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'quantity' : IDL.Float64,
  'costBasis' : IDL.Float64,
  'walletAddressLabel' : IDL.Text,
  'symbol' : IDL.Text,
});
export const TransactionDTO = IDL.Record({
  'id' : TransactionId,
  'priceAtTime' : IDL.Float64,
  'transactionType' : IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
  'totalValue' : IDL.Float64,
  'date' : IDL.Int,
  'notes' : IDL.Text,
  'quantity' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addHolding' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
      [HoldingId],
      [],
    ),
  'addTransaction' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [TransactionId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteTransaction' : IDL.Func([TransactionId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlatformStats' : IDL.Func([], [PlatformStats], []),
  'getPrices' : IDL.Func([], [IDL.Text], []),
  'getReferralLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(ReferralLeaderboardEntry)],
      ['query'],
    ),
  'getReferralStats' : IDL.Func([UserId], [ReferralStats], ['query']),
  'getUserHoldings' : IDL.Func([UserId], [IDL.Vec(HoldingDTO)], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTransactions' : IDL.Func([UserId], [IDL.Vec(TransactionDTO)], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeHolding' : IDL.Func([HoldingId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateHolding' : IDL.Func(
      [HoldingId, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HoldingId = IDL.Nat;
  const TransactionId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PlatformStats = IDL.Record({
    'activeUsers' : IDL.Nat,
    'totalHoldings' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'suspendedUsers' : IDL.Nat,
    'totalTransactions' : IDL.Nat,
  });
  const ReferralLeaderboardEntry = IDL.Record({
    'username' : IDL.Text,
    'referralCount' : IDL.Nat,
  });
  const UserId = IDL.Principal;
  const ReferralStats = IDL.Record({
    'referredUsers' : IDL.Vec(IDL.Text),
    'referralCount' : IDL.Nat,
  });
  const HoldingDTO = IDL.Record({
    'id' : HoldingId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'quantity' : IDL.Float64,
    'costBasis' : IDL.Float64,
    'walletAddressLabel' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const TransactionDTO = IDL.Record({
    'id' : TransactionId,
    'priceAtTime' : IDL.Float64,
    'transactionType' : IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
    'totalValue' : IDL.Float64,
    'date' : IDL.Int,
    'notes' : IDL.Text,
    'quantity' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addHolding' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
        [HoldingId],
        [],
      ),
    'addTransaction' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [TransactionId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteTransaction' : IDL.Func([TransactionId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlatformStats' : IDL.Func([], [PlatformStats], []),
    'getPrices' : IDL.Func([], [IDL.Text], []),
    'getReferralLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(ReferralLeaderboardEntry)],
        ['query'],
      ),
    'getReferralStats' : IDL.Func([UserId], [ReferralStats], ['query']),
    'getUserHoldings' : IDL.Func([UserId], [IDL.Vec(HoldingDTO)], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTransactions' : IDL.Func([UserId], [IDL.Vec(TransactionDTO)], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeHolding' : IDL.Func([HoldingId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateHolding' : IDL.Func(
        [HoldingId, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };